/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActivityLog : An event returned by the Activity Logs API.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivityLog {
    /// The ID of the event.
    #[serde(rename = "id")]
    pub id: String,
    /// The timestamp of the event in seconds since the Unix epoch.
    #[serde(rename = "timestamp")]
    pub timestamp: f64,
    #[serde(rename = "actor")]
    pub actor: Box<models::ActivityLogActor>,
    #[serde(rename = "action")]
    pub action: Box<models::ActivityLogAction>,
    #[serde(rename = "entity")]
    pub entity: Box<models::ActivityLogEntity>,
    #[serde(rename = "context")]
    pub context: Box<models::ActivityLogContext>,
}

impl ActivityLog {
    /// An event returned by the Activity Logs API.
    pub fn new(id: String, timestamp: f64, actor: models::ActivityLogActor, action: models::ActivityLogAction, entity: models::ActivityLogEntity, context: models::ActivityLogContext) -> ActivityLog {
        ActivityLog {
            id,
            timestamp,
            actor: Box::new(actor),
            action: Box::new(action),
            entity: Box::new(entity),
            context: Box::new(context),
        }
    }
}

