/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActivityLogFileEntity : A Figma Design or FigJam file
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivityLogFileEntity {
    /// The type of entity.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Unique identifier of the file.
    #[serde(rename = "key")]
    pub key: String,
    /// Name of the file.
    #[serde(rename = "name")]
    pub name: String,
    /// Indicates if the object is a file on Figma Design or FigJam.
    #[serde(rename = "editor_type")]
    pub editor_type: EditorType,
    #[serde(rename = "link_access")]
    pub link_access: models::LinkAccess,
    /// Access policy for users who have the link to the file's prototype.
    #[serde(rename = "proto_link_access")]
    pub proto_link_access: ProtoLinkAccess,
}

impl ActivityLogFileEntity {
    /// A Figma Design or FigJam file
    pub fn new(r#type: Type, key: String, name: String, editor_type: EditorType, link_access: models::LinkAccess, proto_link_access: ProtoLinkAccess) -> ActivityLogFileEntity {
        ActivityLogFileEntity {
            r#type,
            key,
            name,
            editor_type,
            link_access,
            proto_link_access,
        }
    }
}
/// The type of entity.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "file")]
    File,
}

impl Default for Type {
    fn default() -> Type {
        Self::File
    }
}
/// Indicates if the object is a file on Figma Design or FigJam.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EditorType {
    #[serde(rename = "figma")]
    Figma,
    #[serde(rename = "figjam")]
    Figjam,
}

impl Default for EditorType {
    fn default() -> EditorType {
        Self::Figma
    }
}
/// Access policy for users who have the link to the file's prototype.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProtoLinkAccess {
    #[serde(rename = "view")]
    View,
    #[serde(rename = "org_view")]
    OrgView,
    #[serde(rename = "inherit")]
    Inherit,
}

impl Default for ProtoLinkAccess {
    fn default() -> ProtoLinkAccess {
        Self::View
    }
}

