/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActivityLogAction : The task or activity the actor performed.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivityLogAction {
    /// The type of the action.
    #[serde(rename = "type")]
    pub r#type: String,
    /// Metadata of the action. Each action type supports its own metadata attributes.
    #[serde(rename = "details")]
    pub details: std::collections::HashMap<String, serde_json::Value>,
}

impl ActivityLogAction {
    /// The task or activity the actor performed.
    pub fn new(r#type: String, details: std::collections::HashMap<String, serde_json::Value>) -> ActivityLogAction {
        ActivityLogAction {
            r#type,
            details,
        }
    }
}

