/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActivityLogWorkspaceEntity : Part of the organizational hierarchy of managing files and users within Figma, only available on the Enterprise Plan
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivityLogWorkspaceEntity {
    /// The type of entity.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Unique identifier of the workspace.
    #[serde(rename = "id")]
    pub id: String,
    /// Name of the workspace.
    #[serde(rename = "name")]
    pub name: String,
}

impl ActivityLogWorkspaceEntity {
    /// Part of the organizational hierarchy of managing files and users within Figma, only available on the Enterprise Plan
    pub fn new(r#type: Type, id: String, name: String) -> ActivityLogWorkspaceEntity {
        ActivityLogWorkspaceEntity {
            r#type,
            id,
            name,
        }
    }
}
/// The type of entity.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "workspace")]
    Workspace,
}

impl Default for Type {
    fn default() -> Type {
        Self::Workspace
    }
}

