/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActivityLogEntity : The resource the actor took the action on. It can be a user, file, project or other resource types.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ActivityLogEntity {
    #[serde(rename="user")]
    User(Box<models::ActivityLogUserEntity>),
    #[serde(rename="file")]
    File(Box<models::ActivityLogFileEntity>),
    #[serde(rename="file_repo")]
    FileRepo(Box<models::ActivityLogFileRepoEntity>),
    #[serde(rename="project")]
    Project(Box<models::ActivityLogProjectEntity>),
    #[serde(rename="team")]
    Team(Box<models::ActivityLogTeamEntity>),
    #[serde(rename="workspace")]
    Workspace(Box<models::ActivityLogWorkspaceEntity>),
    #[serde(rename="org")]
    Org(Box<models::ActivityLogOrgEntity>),
    #[serde(rename="plugin")]
    Plugin(Box<models::ActivityLogPluginEntity>),
    #[serde(rename="widget")]
    Widget(Box<models::ActivityLogWidgetEntity>),
}

impl Default for ActivityLogEntity {
    fn default() -> Self {
        Self::User(Default::default())
    }
}

/// Indicates if the object is a widget available on Figma Design or FigJam.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EditorType {
    #[serde(rename = "figma")]
    Figma,
    #[serde(rename = "figjam")]
    Figjam,
}

impl Default for EditorType {
    fn default() -> EditorType {
        Self::Figma
    }
}
/// Access policy for users who have the link to the file's prototype.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProtoLinkAccess {
    #[serde(rename = "view")]
    View,
    #[serde(rename = "org_view")]
    OrgView,
    #[serde(rename = "inherit")]
    Inherit,
}

impl Default for ProtoLinkAccess {
    fn default() -> ProtoLinkAccess {
        Self::View
    }
}

