/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActivityLogFileRepoEntity : A file branch that diverges from and can be merged back into the main file
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivityLogFileRepoEntity {
    /// The type of entity.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Unique identifier of the file branch.
    #[serde(rename = "id")]
    pub id: String,
    /// Name of the file.
    #[serde(rename = "name")]
    pub name: String,
    /// Key of the main file.
    #[serde(rename = "main_file_key")]
    pub main_file_key: String,
}

impl ActivityLogFileRepoEntity {
    /// A file branch that diverges from and can be merged back into the main file
    pub fn new(r#type: Type, id: String, name: String, main_file_key: String) -> ActivityLogFileRepoEntity {
        ActivityLogFileRepoEntity {
            r#type,
            id,
            name,
            main_file_key,
        }
    }
}
/// The type of entity.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "file_repo")]
    FileRepo,
}

impl Default for Type {
    fn default() -> Type {
        Self::FileRepo
    }
}

