/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActivityLogPluginEntity : A Figma plugin
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivityLogPluginEntity {
    /// The type of entity.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Unique identifier of the plugin.
    #[serde(rename = "id")]
    pub id: String,
    /// Name of the plugin.
    #[serde(rename = "name")]
    pub name: String,
    /// Indicates if the object is a plugin is available on Figma Design or FigJam.
    #[serde(rename = "editor_type")]
    pub editor_type: EditorType,
}

impl ActivityLogPluginEntity {
    /// A Figma plugin
    pub fn new(r#type: Type, id: String, name: String, editor_type: EditorType) -> ActivityLogPluginEntity {
        ActivityLogPluginEntity {
            r#type,
            id,
            name,
            editor_type,
        }
    }
}
/// The type of entity.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "plugin")]
    Plugin,
}

impl Default for Type {
    fn default() -> Type {
        Self::Plugin
    }
}
/// Indicates if the object is a plugin is available on Figma Design or FigJam.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EditorType {
    #[serde(rename = "figma")]
    Figma,
    #[serde(rename = "figjam")]
    Figjam,
}

impl Default for EditorType {
    fn default() -> EditorType {
        Self::Figma
    }
}

