/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActivityLogContext : Contextual information about the event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivityLogContext {
    /// The third-party application that triggered the event, if applicable.
    #[serde(rename = "client_name", deserialize_with = "Option::deserialize")]
    pub client_name: Option<serde_json::Value>,
    /// The IP address from of the client that sent the event request.
    #[serde(rename = "ip_address")]
    pub ip_address: String,
    /// If Figma's Support team triggered the event. This is either true or false.
    #[serde(rename = "is_figma_support_team_action")]
    pub is_figma_support_team_action: bool,
    /// The id of the organization where the event took place.
    #[serde(rename = "org_id")]
    pub org_id: String,
    /// The id of the team where the event took place -- if this took place in a specific team.
    #[serde(rename = "team_id", deserialize_with = "Option::deserialize")]
    pub team_id: Option<serde_json::Value>,
}

impl ActivityLogContext {
    /// Contextual information about the event.
    pub fn new(client_name: Option<serde_json::Value>, ip_address: String, is_figma_support_team_action: bool, org_id: String, team_id: Option<serde_json::Value>) -> ActivityLogContext {
        ActivityLogContext {
            client_name,
            ip_address,
            is_figma_support_team_action,
            org_id,
            team_id,
        }
    }
}

