/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActivityLogUserEntity : A Figma user
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivityLogUserEntity {
    /// The type of entity.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Unique stable id of the user.
    #[serde(rename = "id")]
    pub id: String,
    /// Name of the user.
    #[serde(rename = "name")]
    pub name: String,
    /// Email associated with the user's account.
    #[serde(rename = "email")]
    pub email: String,
}

impl ActivityLogUserEntity {
    /// A Figma user
    pub fn new(r#type: Type, id: String, name: String, email: String) -> ActivityLogUserEntity {
        ActivityLogUserEntity {
            r#type,
            id,
            name,
            email,
        }
    }
}
/// The type of entity.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "user")]
    User,
}

impl Default for Type {
    fn default() -> Type {
        Self::User
    }
}

