/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DevResource : A dev resource in a file
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DevResource {
    /// Unique identifier of the dev resource
    #[serde(rename = "id")]
    pub id: String,
    /// The name of the dev resource.
    #[serde(rename = "name")]
    pub name: String,
    /// The URL of the dev resource.
    #[serde(rename = "url")]
    pub url: String,
    /// The file key where the dev resource belongs.
    #[serde(rename = "file_key")]
    pub file_key: String,
    /// The target node to attach the dev resource to.
    #[serde(rename = "node_id")]
    pub node_id: String,
}

impl DevResource {
    /// A dev resource in a file
    pub fn new(id: String, name: String, url: String, file_key: String, node_id: String) -> DevResource {
        DevResource {
            id,
            name,
            url,
            file_key,
            node_id,
        }
    }
}

