/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DevStatusTraitDevStatus : Represents whether or not a node has a particular handoff (or dev) status applied to it.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DevStatusTraitDevStatus {
    #[serde(rename = "type")]
    pub r#type: Type,
    /// An optional field where the designer can add more information about the design and what has changed.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl DevStatusTraitDevStatus {
    /// Represents whether or not a node has a particular handoff (or dev) status applied to it.
    pub fn new(r#type: Type) -> DevStatusTraitDevStatus {
        DevStatusTraitDevStatus {
            r#type,
            description: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "NONE")]
    None,
    #[serde(rename = "READY_FOR_DEV")]
    ReadyForDev,
    #[serde(rename = "COMPLETED")]
    Completed,
}

impl Default for Type {
    fn default() -> Type {
        Self::None
    }
}

