/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetImageFills200ResponseMeta {
    /// A map of image references to URLs of the image fills.
    #[serde(rename = "images")]
    pub images: std::collections::HashMap<String, String>,
}

impl GetImageFills200ResponseMeta {
    pub fn new(images: std::collections::HashMap<String, String>) -> GetImageFills200ResponseMeta {
        GetImageFills200ResponseMeta {
            images,
        }
    }
}

