/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMe200Response {
    /// Unique stable id of the user.
    #[serde(rename = "id")]
    pub id: String,
    /// Name of the user.
    #[serde(rename = "handle")]
    pub handle: String,
    /// URL link to the user's profile image.
    #[serde(rename = "img_url")]
    pub img_url: String,
    /// Email associated with the user's account. This property is only present on the /v1/me endpoint.
    #[serde(rename = "email")]
    pub email: String,
}

impl GetMe200Response {
    pub fn new(id: String, handle: String, img_url: String, email: String) -> GetMe200Response {
        GetMe200Response {
            id,
            handle,
            img_url,
            email,
        }
    }
}

