/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectFiles200ResponseFilesInner {
    /// The file's key.
    #[serde(rename = "key")]
    pub key: String,
    /// The file's name.
    #[serde(rename = "name")]
    pub name: String,
    /// The file's thumbnail URL.
    #[serde(rename = "thumbnail_url", skip_serializing_if = "Option::is_none")]
    pub thumbnail_url: Option<String>,
    /// The UTC ISO 8601 time at which the file was last modified.
    #[serde(rename = "last_modified")]
    pub last_modified: String,
}

impl GetProjectFiles200ResponseFilesInner {
    pub fn new(key: String, name: String, last_modified: String) -> GetProjectFiles200ResponseFilesInner {
        GetProjectFiles200ResponseFilesInner {
            key,
            name,
            thumbnail_url: None,
            last_modified,
        }
    }
}

