/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetImages200Response {
    /// For successful requests, this value is always `null`.
    #[serde(rename = "err")]
    pub err: models::Null,
    /// A map from node IDs to URLs of the rendered images.
    #[serde(rename = "images")]
    pub images: std::collections::HashMap<String, serde_json::Value>,
}

impl GetImages200Response {
    pub fn new(err: models::Null, images: std::collections::HashMap<String, serde_json::Value>) -> GetImages200Response {
        GetImages200Response {
            err,
            images,
        }
    }
}

