/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLibraryAnalyticsComponentActions200Response {
    #[serde(rename = "rows")]
    pub rows: Box<models::GetLibraryAnalyticsComponentActions200ResponseRows>,
    /// Whether there is a next page of data that can be fetched.
    #[serde(rename = "next_page")]
    pub next_page: bool,
    /// The cursor to use to fetch the next page of data. Not present if next_page is false.
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

impl GetLibraryAnalyticsComponentActions200Response {
    pub fn new(rows: models::GetLibraryAnalyticsComponentActions200ResponseRows, next_page: bool) -> GetLibraryAnalyticsComponentActions200Response {
        GetLibraryAnalyticsComponentActions200Response {
            rows: Box::new(rows),
            next_page,
            cursor: None,
        }
    }
}

