/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetLibraryAnalyticsComponentUsages200ResponseRows : An array of analytics data.
/// An array of analytics data.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLibraryAnalyticsComponentUsages200ResponseRows {
    Array(Vec<models::LibraryAnalyticsComponentUsagesByAsset>),
    Array(Vec<models::LibraryAnalyticsComponentUsagesByFile>),
}

impl Default for GetLibraryAnalyticsComponentUsages200ResponseRows {
    fn default() -> Self {
        Self::Array(Default::default())
    }
}

