/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetActivityLogs401Response {
    /// For erroneous requests, this value is always `true`.
    #[serde(rename = "error")]
    pub error: bool,
    /// Status code
    #[serde(rename = "status")]
    pub status: Status,
    /// A string describing the error
    #[serde(rename = "message")]
    pub message: String,
}

impl GetActivityLogs401Response {
    pub fn new(error: bool, status: Status, message: String) -> GetActivityLogs401Response {
        GetActivityLogs401Response {
            error,
            status,
            message,
        }
    }
}
/// Status code
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "401")]
    Variant401,
}

impl Default for Status {
    fn default() -> Status {
        Self::Variant401
    }
}

