/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetActivityLogs200ResponseMeta {
    /// An array of activity logs sorted by timestamp in ascending order by default.
    #[serde(rename = "activity_logs", skip_serializing_if = "Option::is_none")]
    pub activity_logs: Option<Vec<models::ActivityLog>>,
    /// Encodes the last event (the most recent event)
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Whether there is a next page of events
    #[serde(rename = "next_page", skip_serializing_if = "Option::is_none")]
    pub next_page: Option<bool>,
}

impl GetActivityLogs200ResponseMeta {
    pub fn new() -> GetActivityLogs200ResponseMeta {
        GetActivityLogs200ResponseMeta {
            activity_logs: None,
            cursor: None,
            next_page: None,
        }
    }
}

