/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetImageFills200Response {
    /// For successful requests, this value is always `false`.
    #[serde(rename = "error")]
    pub error: bool,
    /// Status code
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "meta")]
    pub meta: Box<models::GetImageFills200ResponseMeta>,
}

impl GetImageFills200Response {
    pub fn new(error: bool, status: Status, meta: models::GetImageFills200ResponseMeta) -> GetImageFills200Response {
        GetImageFills200Response {
            error,
            status,
            meta: Box::new(meta),
        }
    }
}
/// Status code
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "200")]
    Variant200,
}

impl Default for Status {
    fn default() -> Status {
        Self::Variant200
    }
}

