/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LibraryAnalyticsComponentActionsByAsset : Library analytics component actions data broken down by asset.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LibraryAnalyticsComponentActionsByAsset {
    /// The date in ISO 8601 format. e.g. 2023-12-13
    #[serde(rename = "week")]
    pub week: String,
    /// Unique, stable id of the component.
    #[serde(rename = "component_key")]
    pub component_key: String,
    /// Name of the component.
    #[serde(rename = "component_name")]
    pub component_name: String,
    /// Unique, stable id of the component set that this component belongs to.
    #[serde(rename = "component_set_key", skip_serializing_if = "Option::is_none")]
    pub component_set_key: Option<String>,
    /// Name of the component set that this component belongs to.
    #[serde(rename = "component_set_name", skip_serializing_if = "Option::is_none")]
    pub component_set_name: Option<String>,
    /// The number of detach events for this period.
    #[serde(rename = "detachments")]
    pub detachments: f64,
    /// The number of insertion events for this period.
    #[serde(rename = "insertions")]
    pub insertions: f64,
}

impl LibraryAnalyticsComponentActionsByAsset {
    /// Library analytics component actions data broken down by asset.
    pub fn new(week: String, component_key: String, component_name: String, detachments: f64, insertions: f64) -> LibraryAnalyticsComponentActionsByAsset {
        LibraryAnalyticsComponentActionsByAsset {
            week,
            component_key,
            component_name,
            component_set_key: None,
            component_set_name: None,
            detachments,
            insertions,
        }
    }
}

