/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LibraryAnalyticsStyleUsagesByFile : Library analytics style usage data broken down by file.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LibraryAnalyticsStyleUsagesByFile {
    /// The name of the file using the library.
    #[serde(rename = "file_name")]
    pub file_name: String,
    /// The name of the team the file belongs to.
    #[serde(rename = "team_name")]
    pub team_name: String,
    /// The name of the workspace that the file belongs to.
    #[serde(rename = "workspace_name", skip_serializing_if = "Option::is_none")]
    pub workspace_name: Option<String>,
    /// The number of times styles from this library are used within the file.
    #[serde(rename = "usages")]
    pub usages: f64,
}

impl LibraryAnalyticsStyleUsagesByFile {
    /// Library analytics style usage data broken down by file.
    pub fn new(file_name: String, team_name: String, usages: f64) -> LibraryAnalyticsStyleUsagesByFile {
        LibraryAnalyticsStyleUsagesByFile {
            file_name,
            team_name,
            workspace_name: None,
            usages,
        }
    }
}

