/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LibraryAnalyticsVariableUsagesByAsset : Library analytics variable usage data broken down by component.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LibraryAnalyticsVariableUsagesByAsset {
    /// Unique, stable id of the variable.
    #[serde(rename = "variable_key")]
    pub variable_key: String,
    /// The name of the variable.
    #[serde(rename = "variable_name")]
    pub variable_name: String,
    /// The type of the variable.
    #[serde(rename = "variable_type")]
    pub variable_type: String,
    /// Unique, stable id of the collection the variable belongs to.
    #[serde(rename = "collection_key")]
    pub collection_key: String,
    /// The name of the collection the variable belongs to.
    #[serde(rename = "collection_name")]
    pub collection_name: String,
    /// The number of usages of the variable within the organization.
    #[serde(rename = "usages")]
    pub usages: f64,
    /// The number of teams using the variable within the organization.
    #[serde(rename = "teams_using")]
    pub teams_using: f64,
    /// The number of files using the variable within the organization.
    #[serde(rename = "files_using")]
    pub files_using: f64,
}

impl LibraryAnalyticsVariableUsagesByAsset {
    /// Library analytics variable usage data broken down by component.
    pub fn new(variable_key: String, variable_name: String, variable_type: String, collection_key: String, collection_name: String, usages: f64, teams_using: f64, files_using: f64) -> LibraryAnalyticsVariableUsagesByAsset {
        LibraryAnalyticsVariableUsagesByAsset {
            variable_key,
            variable_name,
            variable_type,
            collection_key,
            collection_name,
            usages,
            teams_using,
            files_using,
        }
    }
}

