/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LibraryAnalyticsComponentActionsByTeam : Library analytics action data broken down by team.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LibraryAnalyticsComponentActionsByTeam {
    /// The date in ISO 8601 format. e.g. 2023-12-13
    #[serde(rename = "week")]
    pub week: String,
    /// The name of the team using the library.
    #[serde(rename = "team_name")]
    pub team_name: String,
    /// The name of the workspace that the team belongs to.
    #[serde(rename = "workspace_name", skip_serializing_if = "Option::is_none")]
    pub workspace_name: Option<String>,
    /// The number of detach events for this period.
    #[serde(rename = "detachments")]
    pub detachments: f64,
    /// The number of insertion events for this period.
    #[serde(rename = "insertions")]
    pub insertions: f64,
}

impl LibraryAnalyticsComponentActionsByTeam {
    /// Library analytics action data broken down by team.
    pub fn new(week: String, team_name: String, detachments: f64, insertions: f64) -> LibraryAnalyticsComponentActionsByTeam {
        LibraryAnalyticsComponentActionsByTeam {
            week,
            team_name,
            workspace_name: None,
            detachments,
            insertions,
        }
    }
}

