/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LibraryAnalyticsStyleActionsByAsset : Library analytics style actions data broken down by asset.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LibraryAnalyticsStyleActionsByAsset {
    /// The date in ISO 8601 format. e.g. 2023-12-13
    #[serde(rename = "week")]
    pub week: String,
    /// Unique, stable id of the style.
    #[serde(rename = "style_key")]
    pub style_key: String,
    /// The name of the style.
    #[serde(rename = "style_name")]
    pub style_name: String,
    /// The type of the style.
    #[serde(rename = "style_type")]
    pub style_type: String,
    /// The number of detach events for this period.
    #[serde(rename = "detachments")]
    pub detachments: f64,
    /// The number of insertion events for this period.
    #[serde(rename = "insertions")]
    pub insertions: f64,
}

impl LibraryAnalyticsStyleActionsByAsset {
    /// Library analytics style actions data broken down by asset.
    pub fn new(week: String, style_key: String, style_name: String, style_type: String, detachments: f64, insertions: f64) -> LibraryAnalyticsStyleActionsByAsset {
        LibraryAnalyticsStyleActionsByAsset {
            week,
            style_key,
            style_name,
            style_type,
            detachments,
            insertions,
        }
    }
}

