/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LibraryAnalyticsVariableActionsByAsset : Library analytics variable actions data broken down by asset.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LibraryAnalyticsVariableActionsByAsset {
    /// The date in ISO 8601 format. e.g. 2023-12-13
    #[serde(rename = "week")]
    pub week: String,
    /// Unique, stable id of the variable.
    #[serde(rename = "variable_key")]
    pub variable_key: String,
    /// The name of the variable.
    #[serde(rename = "variable_name")]
    pub variable_name: String,
    /// The type of the variable.
    #[serde(rename = "variable_type")]
    pub variable_type: String,
    /// Unique, stable id of the collection the variable belongs to.
    #[serde(rename = "collection_key")]
    pub collection_key: String,
    /// The name of the collection the variable belongs to.
    #[serde(rename = "collection_name")]
    pub collection_name: String,
    /// The number of detach events for this period.
    #[serde(rename = "detachments")]
    pub detachments: f64,
    /// The number of insertion events for this period.
    #[serde(rename = "insertions")]
    pub insertions: f64,
}

impl LibraryAnalyticsVariableActionsByAsset {
    /// Library analytics variable actions data broken down by asset.
    pub fn new(week: String, variable_key: String, variable_name: String, variable_type: String, collection_key: String, collection_name: String, detachments: f64, insertions: f64) -> LibraryAnalyticsVariableActionsByAsset {
        LibraryAnalyticsVariableActionsByAsset {
            week,
            variable_key,
            variable_name,
            variable_type,
            collection_key,
            collection_name,
            detachments,
            insertions,
        }
    }
}

