/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LibraryAnalyticsComponentUsagesByAsset : Library analytics component usage data broken down by component.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LibraryAnalyticsComponentUsagesByAsset {
    /// Unique, stable id of the component.
    #[serde(rename = "component_key")]
    pub component_key: String,
    /// Name of the component.
    #[serde(rename = "component_name")]
    pub component_name: String,
    /// Unique, stable id of the component set that this component belongs to.
    #[serde(rename = "component_set_key", skip_serializing_if = "Option::is_none")]
    pub component_set_key: Option<String>,
    /// Name of the component set that this component belongs to.
    #[serde(rename = "component_set_name", skip_serializing_if = "Option::is_none")]
    pub component_set_name: Option<String>,
    /// The number of instances of the component within the organization.
    #[serde(rename = "usages")]
    pub usages: f64,
    /// The number of teams using the component within the organization.
    #[serde(rename = "teams_using")]
    pub teams_using: f64,
    /// The number of files using the component within the organization.
    #[serde(rename = "files_using")]
    pub files_using: f64,
}

impl LibraryAnalyticsComponentUsagesByAsset {
    /// Library analytics component usage data broken down by component.
    pub fn new(component_key: String, component_name: String, usages: f64, teams_using: f64, files_using: f64) -> LibraryAnalyticsComponentUsagesByAsset {
        LibraryAnalyticsComponentUsagesByAsset {
            component_key,
            component_name,
            component_set_key: None,
            component_set_name: None,
            usages,
            teams_using,
            files_using,
        }
    }
}

