/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LibraryAnalyticsStyleUsagesByAsset : Library analytics style usage data broken down by component.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LibraryAnalyticsStyleUsagesByAsset {
    /// Unique, stable id of the style.
    #[serde(rename = "style_key")]
    pub style_key: String,
    /// The name of the style.
    #[serde(rename = "style_name")]
    pub style_name: String,
    /// The type of the style.
    #[serde(rename = "style_type")]
    pub style_type: String,
    /// The number of usages of the style within the organization.
    #[serde(rename = "usages")]
    pub usages: f64,
    /// The number of teams using the style within the organization.
    #[serde(rename = "teams_using")]
    pub teams_using: f64,
    /// The number of files using the style within the organization.
    #[serde(rename = "files_using")]
    pub files_using: f64,
}

impl LibraryAnalyticsStyleUsagesByAsset {
    /// Library analytics style usage data broken down by component.
    pub fn new(style_key: String, style_name: String, style_type: String, usages: f64, teams_using: f64, files_using: f64) -> LibraryAnalyticsStyleUsagesByAsset {
        LibraryAnalyticsStyleUsagesByAsset {
            style_key,
            style_name,
            style_type,
            usages,
            teams_using,
            files_using,
        }
    }
}

