/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PaymentInformation : An object describing a user's payment information for a plugin, widget, or Community file.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentInformation {
    /// The ID of the user whose payment information was queried. Can be used to verify the validity of a response.
    #[serde(rename = "user_id")]
    pub user_id: String,
    /// The ID of the plugin, widget, or Community file that was queried. Can be used to verify the validity of a response.
    #[serde(rename = "resource_id")]
    pub resource_id: String,
    /// The type of the resource.
    #[serde(rename = "resource_type")]
    pub resource_type: ResourceType,
    #[serde(rename = "payment_status")]
    pub payment_status: Box<models::PaymentStatus>,
    /// The UTC ISO 8601 timestamp indicating when the user purchased the resource. No value is given if the user has never purchased the resource.    Note that a value will still be returned if the user had purchased the resource, but no longer has active access to it (e.g. purchase refunded, subscription ended).
    #[serde(rename = "date_of_purchase", skip_serializing_if = "Option::is_none")]
    pub date_of_purchase: Option<String>,
}

impl PaymentInformation {
    /// An object describing a user's payment information for a plugin, widget, or Community file.
    pub fn new(user_id: String, resource_id: String, resource_type: ResourceType, payment_status: models::PaymentStatus) -> PaymentInformation {
        PaymentInformation {
            user_id,
            resource_id,
            resource_type,
            payment_status: Box::new(payment_status),
            date_of_purchase: None,
        }
    }
}
/// The type of the resource.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ResourceType {
    #[serde(rename = "PLUGIN")]
    Plugin,
    #[serde(rename = "WIDGET")]
    Widget,
    #[serde(rename = "COMMUNITY_FILE")]
    CommunityFile,
}

impl Default for ResourceType {
    fn default() -> ResourceType {
        Self::Plugin
    }
}

