/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PaymentStatus : An object describing the user's payment status.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentStatus {
    /// The current payment status of the user on the resource, as a string enum:    - `UNPAID`: user has not paid for the resource - `PAID`: user has an active purchase on the resource - `TRIAL`: user is in the trial period for a subscription resource
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
}

impl PaymentStatus {
    /// An object describing the user's payment status.
    pub fn new() -> PaymentStatus {
        PaymentStatus {
            r#type: None,
        }
    }
}
/// The current payment status of the user on the resource, as a string enum:    - `UNPAID`: user has not paid for the resource - `PAID`: user has an active purchase on the resource - `TRIAL`: user is in the trial period for a subscription resource
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "UNPAID")]
    Unpaid,
    #[serde(rename = "PAID")]
    Paid,
    #[serde(rename = "TRIAL")]
    Trial,
}

impl Default for Type {
    fn default() -> Type {
        Self::Unpaid
    }
}

