/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostCommentRequest {
    /// The text contents of the comment to post.
    #[serde(rename = "message")]
    pub message: String,
    /// The ID of the comment to reply to, if any. This must be a root comment. You cannot reply to other replies (a comment that has a parent_id).
    #[serde(rename = "comment_id", skip_serializing_if = "Option::is_none")]
    pub comment_id: Option<String>,
    #[serde(rename = "client_meta", skip_serializing_if = "Option::is_none")]
    pub client_meta: Option<Box<models::PostCommentRequestClientMeta>>,
}

impl PostCommentRequest {
    pub fn new(message: String) -> PostCommentRequest {
        PostCommentRequest {
            message,
            comment_id: None,
            client_meta: None,
        }
    }
}

