/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostDevResources200ResponseErrorsInner {
    /// The file key.
    #[serde(rename = "file_key", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub file_key: Option<Option<serde_json::Value>>,
    /// The node id.
    #[serde(rename = "node_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub node_id: Option<Option<serde_json::Value>>,
    /// The error message.
    #[serde(rename = "error")]
    pub error: String,
}

impl PostDevResources200ResponseErrorsInner {
    pub fn new(error: String) -> PostDevResources200ResponseErrorsInner {
        PostDevResources200ResponseErrorsInner {
            file_key: None,
            node_id: None,
            error,
        }
    }
}

