/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostVariablesRequest {
    /// For creating, updating, and deleting variable collections.
    #[serde(rename = "variableCollections", skip_serializing_if = "Option::is_none")]
    pub variable_collections: Option<Vec<models::VariableCollectionChange>>,
    /// For creating, updating, and deleting modes within variable collections.
    #[serde(rename = "variableModes", skip_serializing_if = "Option::is_none")]
    pub variable_modes: Option<Vec<models::VariableModeChange>>,
    /// For creating, updating, and deleting variables.
    #[serde(rename = "variables", skip_serializing_if = "Option::is_none")]
    pub variables: Option<Vec<models::VariableChange>>,
    /// For setting a specific value, given a variable and a mode.
    #[serde(rename = "variableModeValues", skip_serializing_if = "Option::is_none")]
    pub variable_mode_values: Option<Vec<models::VariableModeValue>>,
}

impl PostVariablesRequest {
    pub fn new() -> PostVariablesRequest {
        PostVariablesRequest {
            variable_collections: None,
            variable_modes: None,
            variables: None,
            variable_mode_values: None,
        }
    }
}

