/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostWebhookRequest {
    #[serde(rename = "event_type")]
    pub event_type: models::WebhookV2Event,
    /// Team id to receive updates about. This is deprecated, use 'context' and 'context_id' instead.
    #[serde(rename = "team_id", skip_serializing_if = "Option::is_none")]
    pub team_id: Option<String>,
    /// Context to create the webhook for. Must be \"team\", \"project\", or \"file\".
    #[serde(rename = "context")]
    pub context: String,
    /// The id of the context you want to receive updates about.
    #[serde(rename = "context_id")]
    pub context_id: String,
    /// The HTTP endpoint that will receive a POST request when the event triggers. Max length 2048 characters.
    #[serde(rename = "endpoint")]
    pub endpoint: String,
    /// String that will be passed back to your webhook endpoint to verify that it is being called by Figma. Max length 100 characters.
    #[serde(rename = "passcode")]
    pub passcode: String,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::WebhookV2Status>,
    /// User provided description or name for the webhook. Max length 150 characters.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl PostWebhookRequest {
    pub fn new(event_type: models::WebhookV2Event, context: String, context_id: String, endpoint: String, passcode: String) -> PostWebhookRequest {
        PostWebhookRequest {
            event_type,
            team_id: None,
            context,
            context_id,
            endpoint,
            passcode,
            status: None,
            description: None,
        }
    }
}

