/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutDevResources200Response {
    /// An array of links updated.
    #[serde(rename = "links_updated", skip_serializing_if = "Option::is_none")]
    pub links_updated: Option<Vec<models::DevResource>>,
    /// An array of errors.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::PutDevResources200ResponseErrorsInner>>,
}

impl PutDevResources200Response {
    pub fn new() -> PutDevResources200Response {
        PutDevResources200Response {
            links_updated: None,
            errors: None,
        }
    }
}

