/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutDevResources200ResponseErrorsInner {
    /// The id of the dev resource.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The error message.
    #[serde(rename = "error")]
    pub error: String,
}

impl PutDevResources200ResponseErrorsInner {
    pub fn new(error: String) -> PutDevResources200ResponseErrorsInner {
        PutDevResources200ResponseErrorsInner {
            id: None,
            error,
        }
    }
}

