/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutWebhookRequest {
    #[serde(rename = "event_type")]
    pub event_type: models::WebhookV2Event,
    /// The HTTP endpoint that will receive a POST request when the event triggers. Max length 2048 characters.
    #[serde(rename = "endpoint")]
    pub endpoint: String,
    /// String that will be passed back to your webhook endpoint to verify that it is being called by Figma. Max length 100 characters.
    #[serde(rename = "passcode")]
    pub passcode: String,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::WebhookV2Status>,
    /// User provided description or name for the webhook. Max length 150 characters.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl PutWebhookRequest {
    pub fn new(event_type: models::WebhookV2Event, endpoint: String, passcode: String) -> PutWebhookRequest {
        PutWebhookRequest {
            event_type,
            endpoint,
            passcode,
            status: None,
            description: None,
        }
    }
}

