/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutDevResourcesRequestDevResourcesInner {
    /// Unique identifier of the dev resource
    #[serde(rename = "id")]
    pub id: String,
    /// The name of the dev resource.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The URL of the dev resource.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl PutDevResourcesRequestDevResourcesInner {
    pub fn new(id: String) -> PutDevResourcesRequestDevResourcesInner {
        PutDevResourcesRequestDevResourcesInner {
            id,
            name: None,
            url: None,
        }
    }
}

