/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookV2Event : An enum representing the possible events that a webhook can subscribe to
/// An enum representing the possible events that a webhook can subscribe to
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WebhookV2Event {
    #[serde(rename = "PING")]
    Ping,
    #[serde(rename = "FILE_UPDATE")]
    FileUpdate,
    #[serde(rename = "FILE_VERSION_UPDATE")]
    FileVersionUpdate,
    #[serde(rename = "FILE_DELETE")]
    FileDelete,
    #[serde(rename = "LIBRARY_PUBLISH")]
    LibraryPublish,
    #[serde(rename = "FILE_COMMENT")]
    FileComment,
    #[serde(rename = "DEV_MODE_STATUS_UPDATE")]
    DevModeStatusUpdate,

}

impl std::fmt::Display for WebhookV2Event {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ping => write!(f, "PING"),
            Self::FileUpdate => write!(f, "FILE_UPDATE"),
            Self::FileVersionUpdate => write!(f, "FILE_VERSION_UPDATE"),
            Self::FileDelete => write!(f, "FILE_DELETE"),
            Self::LibraryPublish => write!(f, "LIBRARY_PUBLISH"),
            Self::FileComment => write!(f, "FILE_COMMENT"),
            Self::DevModeStatusUpdate => write!(f, "DEV_MODE_STATUS_UPDATE"),
        }
    }
}

impl Default for WebhookV2Event {
    fn default() -> WebhookV2Event {
        Self::Ping
    }
}

