/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookV2ResponseInfo : Information regarding the reply sent back from a webhook endpoint
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookV2ResponseInfo {
    /// HTTP status code of the response
    #[serde(rename = "status")]
    pub status: String,
    /// UTC ISO 8601 timestamp of when the response was received
    #[serde(rename = "received_at")]
    pub received_at: String,
}

impl WebhookV2ResponseInfo {
    /// Information regarding the reply sent back from a webhook endpoint
    pub fn new(status: String, received_at: String) -> WebhookV2ResponseInfo {
        WebhookV2ResponseInfo {
            status,
            received_at,
        }
    }
}

