/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookV2Request : Information regarding the most recent interactions sent to a webhook endpoint
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookV2Request {
    /// The ID of the webhook the requests were sent to
    #[serde(rename = "webhook_id")]
    pub webhook_id: String,
    #[serde(rename = "request_info")]
    pub request_info: Box<models::WebhookV2RequestInfo>,
    #[serde(rename = "response_info")]
    pub response_info: Box<models::WebhookV2ResponseInfo>,
    /// Error message for this request. NULL if no error occurred
    #[serde(rename = "error_msg", deserialize_with = "Option::deserialize")]
    pub error_msg: Option<serde_json::Value>,
}

impl WebhookV2Request {
    /// Information regarding the most recent interactions sent to a webhook endpoint
    pub fn new(webhook_id: String, request_info: models::WebhookV2RequestInfo, response_info: models::WebhookV2ResponseInfo, error_msg: Option<serde_json::Value>) -> WebhookV2Request {
        WebhookV2Request {
            webhook_id,
            request_info: Box::new(request_info),
            response_info: Box::new(response_info),
            error_msg,
        }
    }
}

