/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookFileVersionUpdatePayload {
    /// The passcode specified when the webhook was created, should match what was initially provided
    #[serde(rename = "passcode")]
    pub passcode: String,
    /// UTC ISO 8601 timestamp of when the event was triggered.
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    /// The id of the webhook that caused the callback
    #[serde(rename = "webhook_id")]
    pub webhook_id: String,
    #[serde(rename = "event_type")]
    pub event_type: EventType,
    /// UTC ISO 8601 timestamp of when the version was created
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Description of the version in the version history
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The key of the file that was updated
    #[serde(rename = "file_key")]
    pub file_key: String,
    /// The name of the file that was updated
    #[serde(rename = "file_name")]
    pub file_name: String,
    #[serde(rename = "triggered_by")]
    pub triggered_by: Box<models::User>,
    /// ID of the published version
    #[serde(rename = "version_id")]
    pub version_id: String,
}

impl WebhookFileVersionUpdatePayload {
    pub fn new(passcode: String, timestamp: String, webhook_id: String, event_type: EventType, created_at: String, file_key: String, file_name: String, triggered_by: models::User, version_id: String) -> WebhookFileVersionUpdatePayload {
        WebhookFileVersionUpdatePayload {
            passcode,
            timestamp,
            webhook_id,
            event_type,
            created_at,
            description: None,
            file_key,
            file_name,
            triggered_by: Box::new(triggered_by),
            version_id,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventType {
    #[serde(rename = "FILE_VERSION_UPDATE")]
    FileVersionUpdate,
}

impl Default for EventType {
    fn default() -> EventType {
        Self::FileVersionUpdate
    }
}

