/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookV2 : A description of an HTTP webhook (from Figma back to your application)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookV2 {
    /// The ID of the webhook
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "event_type")]
    pub event_type: models::WebhookV2Event,
    /// The team id you are subscribed to for updates. This is deprecated, use context and context_id instead
    #[serde(rename = "team_id")]
    pub team_id: String,
    /// The type of context this webhook is attached to. The value will be \"PROJECT\", \"TEAM\", or \"FILE\"
    #[serde(rename = "context")]
    pub context: String,
    /// The ID of the context this webhook is attached to
    #[serde(rename = "context_id")]
    pub context_id: String,
    /// The plan API ID of the team or organization where this webhook was created
    #[serde(rename = "plan_api_id")]
    pub plan_api_id: String,
    #[serde(rename = "status")]
    pub status: models::WebhookV2Status,
    /// The client ID of the OAuth application that registered this webhook, if any
    #[serde(rename = "client_id", deserialize_with = "Option::deserialize")]
    pub client_id: Option<serde_json::Value>,
    /// The passcode that will be passed back to the webhook endpoint. For security, when using the GET endpoints, the value is an empty string
    #[serde(rename = "passcode")]
    pub passcode: String,
    /// The endpoint that will be hit when the webhook is triggered
    #[serde(rename = "endpoint")]
    pub endpoint: String,
    /// Optional user-provided description or name for the webhook. This is provided to help make maintaining a number of webhooks more convenient. Max length 140 characters.
    #[serde(rename = "description", deserialize_with = "Option::deserialize")]
    pub description: Option<serde_json::Value>,
}

impl WebhookV2 {
    /// A description of an HTTP webhook (from Figma back to your application)
    pub fn new(id: String, event_type: models::WebhookV2Event, team_id: String, context: String, context_id: String, plan_api_id: String, status: models::WebhookV2Status, client_id: Option<serde_json::Value>, passcode: String, endpoint: String, description: Option<serde_json::Value>) -> WebhookV2 {
        WebhookV2 {
            id,
            event_type,
            team_id,
            context,
            context_id,
            plan_api_id,
            status,
            client_id,
            passcode,
            endpoint,
            description,
        }
    }
}

