/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookLibraryPublishPayload {
    /// The passcode specified when the webhook was created, should match what was initially provided
    #[serde(rename = "passcode")]
    pub passcode: String,
    /// UTC ISO 8601 timestamp of when the event was triggered.
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    /// The id of the webhook that caused the callback
    #[serde(rename = "webhook_id")]
    pub webhook_id: String,
    #[serde(rename = "event_type")]
    pub event_type: EventType,
    /// Components that were created by the library publish
    #[serde(rename = "created_components")]
    pub created_components: Vec<models::LibraryItemData>,
    /// Styles that were created by the library publish
    #[serde(rename = "created_styles")]
    pub created_styles: Vec<models::LibraryItemData>,
    /// Variables that were created by the library publish
    #[serde(rename = "created_variables")]
    pub created_variables: Vec<models::LibraryItemData>,
    /// Components that were modified by the library publish
    #[serde(rename = "modified_components")]
    pub modified_components: Vec<models::LibraryItemData>,
    /// Styles that were modified by the library publish
    #[serde(rename = "modified_styles")]
    pub modified_styles: Vec<models::LibraryItemData>,
    /// Variables that were modified by the library publish
    #[serde(rename = "modified_variables")]
    pub modified_variables: Vec<models::LibraryItemData>,
    /// Components that were deleted by the library publish
    #[serde(rename = "deleted_components")]
    pub deleted_components: Vec<models::LibraryItemData>,
    /// Styles that were deleted by the library publish
    #[serde(rename = "deleted_styles")]
    pub deleted_styles: Vec<models::LibraryItemData>,
    /// Variables that were deleted by the library publish
    #[serde(rename = "deleted_variables")]
    pub deleted_variables: Vec<models::LibraryItemData>,
    /// Description of the library publish
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The key of the file that was published
    #[serde(rename = "file_key")]
    pub file_key: String,
    /// The name of the file that was published
    #[serde(rename = "file_name")]
    pub file_name: String,
    #[serde(rename = "library_item")]
    pub library_item: Box<models::LibraryItemData>,
    #[serde(rename = "triggered_by")]
    pub triggered_by: Box<models::User>,
}

impl WebhookLibraryPublishPayload {
    pub fn new(passcode: String, timestamp: String, webhook_id: String, event_type: EventType, created_components: Vec<models::LibraryItemData>, created_styles: Vec<models::LibraryItemData>, created_variables: Vec<models::LibraryItemData>, modified_components: Vec<models::LibraryItemData>, modified_styles: Vec<models::LibraryItemData>, modified_variables: Vec<models::LibraryItemData>, deleted_components: Vec<models::LibraryItemData>, deleted_styles: Vec<models::LibraryItemData>, deleted_variables: Vec<models::LibraryItemData>, file_key: String, file_name: String, library_item: models::LibraryItemData, triggered_by: models::User) -> WebhookLibraryPublishPayload {
        WebhookLibraryPublishPayload {
            passcode,
            timestamp,
            webhook_id,
            event_type,
            created_components,
            created_styles,
            created_variables,
            modified_components,
            modified_styles,
            modified_variables,
            deleted_components,
            deleted_styles,
            deleted_variables,
            description: None,
            file_key,
            file_name,
            library_item: Box::new(library_item),
            triggered_by: Box::new(triggered_by),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventType {
    #[serde(rename = "LIBRARY_PUBLISH")]
    LibraryPublish,
}

impl Default for EventType {
    fn default() -> EventType {
        Self::LibraryPublish
    }
}

