/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookFileCommentPayload {
    /// The passcode specified when the webhook was created, should match what was initially provided
    #[serde(rename = "passcode")]
    pub passcode: String,
    /// UTC ISO 8601 timestamp of when the event was triggered.
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    /// The id of the webhook that caused the callback
    #[serde(rename = "webhook_id")]
    pub webhook_id: String,
    #[serde(rename = "event_type")]
    pub event_type: EventType,
    /// Contents of the comment itself
    #[serde(rename = "comment")]
    pub comment: Vec<models::CommentFragment>,
    /// Unique identifier for comment
    #[serde(rename = "comment_id")]
    pub comment_id: String,
    /// The UTC ISO 8601 time at which the comment was left
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// The key of the file that was commented on
    #[serde(rename = "file_key")]
    pub file_key: String,
    /// The name of the file that was commented on
    #[serde(rename = "file_name")]
    pub file_name: String,
    /// Users that were mentioned in the comment
    #[serde(rename = "mentions", skip_serializing_if = "Option::is_none")]
    pub mentions: Option<Vec<models::User>>,
    #[serde(rename = "triggered_by")]
    pub triggered_by: Box<models::User>,
}

impl WebhookFileCommentPayload {
    pub fn new(passcode: String, timestamp: String, webhook_id: String, event_type: EventType, comment: Vec<models::CommentFragment>, comment_id: String, created_at: String, file_key: String, file_name: String, triggered_by: models::User) -> WebhookFileCommentPayload {
        WebhookFileCommentPayload {
            passcode,
            timestamp,
            webhook_id,
            event_type,
            comment,
            comment_id,
            created_at,
            file_key,
            file_name,
            mentions: None,
            triggered_by: Box::new(triggered_by),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventType {
    #[serde(rename = "FILE_COMMENT")]
    FileComment,
}

impl Default for EventType {
    fn default() -> EventType {
        Self::FileComment
    }
}

