/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookV2RequestInfo : Information regarding the request sent to a webhook endpoint
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookV2RequestInfo {
    /// The ID of the webhook
    #[serde(rename = "id")]
    pub id: String,
    /// The actual endpoint the request was sent to
    #[serde(rename = "endpoint")]
    pub endpoint: String,
    /// The contents of the request that was sent to the endpoint
    #[serde(rename = "payload")]
    pub payload: serde_json::Value,
    /// UTC ISO 8601 timestamp of when the request was sent
    #[serde(rename = "sent_at")]
    pub sent_at: String,
}

impl WebhookV2RequestInfo {
    /// Information regarding the request sent to a webhook endpoint
    pub fn new(id: String, endpoint: String, payload: serde_json::Value, sent_at: String) -> WebhookV2RequestInfo {
        WebhookV2RequestInfo {
            id,
            endpoint,
            payload,
            sent_at,
        }
    }
}

