/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.35.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`get_library_analytics_component_actions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLibraryAnalyticsComponentActionsError {
    Status400(models::GetTeamProjects400Response),
    Status401(models::GetActivityLogs401Response),
    Status403(models::GetActivityLogs403Response),
    Status429(models::GetActivityLogs429Response),
    Status500(models::DeleteWebhook500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_library_analytics_component_usages`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLibraryAnalyticsComponentUsagesError {
    Status400(models::GetTeamProjects400Response),
    Status401(models::GetActivityLogs401Response),
    Status403(models::GetActivityLogs403Response),
    Status429(models::GetActivityLogs429Response),
    Status500(models::DeleteWebhook500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_library_analytics_style_actions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLibraryAnalyticsStyleActionsError {
    Status400(models::GetTeamProjects400Response),
    Status401(models::GetActivityLogs401Response),
    Status403(models::GetActivityLogs403Response),
    Status429(models::GetActivityLogs429Response),
    Status500(models::DeleteWebhook500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_library_analytics_style_usages`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLibraryAnalyticsStyleUsagesError {
    Status400(models::GetTeamProjects400Response),
    Status401(models::GetActivityLogs401Response),
    Status403(models::GetActivityLogs403Response),
    Status429(models::GetActivityLogs429Response),
    Status500(models::DeleteWebhook500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_library_analytics_variable_actions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLibraryAnalyticsVariableActionsError {
    Status400(models::GetTeamProjects400Response),
    Status401(models::GetActivityLogs401Response),
    Status403(models::GetActivityLogs403Response),
    Status429(models::GetActivityLogs429Response),
    Status500(models::DeleteWebhook500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_library_analytics_variable_usages`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLibraryAnalyticsVariableUsagesError {
    Status400(models::GetTeamProjects400Response),
    Status401(models::GetActivityLogs401Response),
    Status403(models::GetActivityLogs403Response),
    Status429(models::GetActivityLogs429Response),
    Status500(models::DeleteWebhook500Response),
    UnknownValue(serde_json::Value),
}


/// Returns a list of library analytics component actions data broken down by the requested dimension.
pub async fn get_library_analytics_component_actions(configuration: &configuration::Configuration, file_key: &str, group_by: &str, cursor: Option<&str>, start_date: Option<&str>, end_date: Option<&str>) -> Result<models::GetLibraryAnalyticsComponentActions200Response, Error<GetLibraryAnalyticsComponentActionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_file_key = file_key;
    let p_group_by = group_by;
    let p_cursor = cursor;
    let p_start_date = start_date;
    let p_end_date = end_date;

    let uri_str = format!("{}/v1/analytics/libraries/{file_key}/component/actions", configuration.base_path, file_key=crate::apis::urlencode(p_file_key));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("group_by", &p_group_by.to_string())]);
    if let Some(ref param_value) = p_start_date {
        req_builder = req_builder.query(&[("start_date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_end_date {
        req_builder = req_builder.query(&[("end_date", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetLibraryAnalyticsComponentActions200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetLibraryAnalyticsComponentActions200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLibraryAnalyticsComponentActionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a list of library analytics component usage data broken down by the requested dimension.
pub async fn get_library_analytics_component_usages(configuration: &configuration::Configuration, file_key: &str, group_by: &str, cursor: Option<&str>) -> Result<models::GetLibraryAnalyticsComponentUsages200Response, Error<GetLibraryAnalyticsComponentUsagesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_file_key = file_key;
    let p_group_by = group_by;
    let p_cursor = cursor;

    let uri_str = format!("{}/v1/analytics/libraries/{file_key}/component/usages", configuration.base_path, file_key=crate::apis::urlencode(p_file_key));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("group_by", &p_group_by.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetLibraryAnalyticsComponentUsages200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetLibraryAnalyticsComponentUsages200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLibraryAnalyticsComponentUsagesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a list of library analytics style actions data broken down by the requested dimension.
pub async fn get_library_analytics_style_actions(configuration: &configuration::Configuration, file_key: &str, group_by: &str, cursor: Option<&str>, start_date: Option<&str>, end_date: Option<&str>) -> Result<models::GetLibraryAnalyticsStyleActions200Response, Error<GetLibraryAnalyticsStyleActionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_file_key = file_key;
    let p_group_by = group_by;
    let p_cursor = cursor;
    let p_start_date = start_date;
    let p_end_date = end_date;

    let uri_str = format!("{}/v1/analytics/libraries/{file_key}/style/actions", configuration.base_path, file_key=crate::apis::urlencode(p_file_key));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("group_by", &p_group_by.to_string())]);
    if let Some(ref param_value) = p_start_date {
        req_builder = req_builder.query(&[("start_date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_end_date {
        req_builder = req_builder.query(&[("end_date", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetLibraryAnalyticsStyleActions200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetLibraryAnalyticsStyleActions200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLibraryAnalyticsStyleActionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a list of library analytics style usage data broken down by the requested dimension.
pub async fn get_library_analytics_style_usages(configuration: &configuration::Configuration, file_key: &str, group_by: &str, cursor: Option<&str>) -> Result<models::GetLibraryAnalyticsStyleUsages200Response, Error<GetLibraryAnalyticsStyleUsagesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_file_key = file_key;
    let p_group_by = group_by;
    let p_cursor = cursor;

    let uri_str = format!("{}/v1/analytics/libraries/{file_key}/style/usages", configuration.base_path, file_key=crate::apis::urlencode(p_file_key));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("group_by", &p_group_by.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetLibraryAnalyticsStyleUsages200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetLibraryAnalyticsStyleUsages200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLibraryAnalyticsStyleUsagesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a list of library analytics variable actions data broken down by the requested dimension.
pub async fn get_library_analytics_variable_actions(configuration: &configuration::Configuration, file_key: &str, group_by: &str, cursor: Option<&str>, start_date: Option<&str>, end_date: Option<&str>) -> Result<models::GetLibraryAnalyticsVariableActions200Response, Error<GetLibraryAnalyticsVariableActionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_file_key = file_key;
    let p_group_by = group_by;
    let p_cursor = cursor;
    let p_start_date = start_date;
    let p_end_date = end_date;

    let uri_str = format!("{}/v1/analytics/libraries/{file_key}/variable/actions", configuration.base_path, file_key=crate::apis::urlencode(p_file_key));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("group_by", &p_group_by.to_string())]);
    if let Some(ref param_value) = p_start_date {
        req_builder = req_builder.query(&[("start_date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_end_date {
        req_builder = req_builder.query(&[("end_date", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetLibraryAnalyticsVariableActions200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetLibraryAnalyticsVariableActions200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLibraryAnalyticsVariableActionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a list of library analytics variable usage data broken down by the requested dimension.
pub async fn get_library_analytics_variable_usages(configuration: &configuration::Configuration, file_key: &str, group_by: &str, cursor: Option<&str>) -> Result<models::GetLibraryAnalyticsVariableUsages200Response, Error<GetLibraryAnalyticsVariableUsagesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_file_key = file_key;
    let p_group_by = group_by;
    let p_cursor = cursor;

    let uri_str = format!("{}/v1/analytics/libraries/{file_key}/variable/usages", configuration.base_path, file_key=crate::apis::urlencode(p_file_key));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("group_by", &p_group_by.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetLibraryAnalyticsVariableUsages200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetLibraryAnalyticsVariableUsages200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLibraryAnalyticsVariableUsagesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

